# Generated by Django 2.2.11 on 2020-10-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('fname', models.CharField(max_length=30)),
                ('fmail', models.EmailField(max_length=254)),
                ('fpass', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='faculty_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('cid', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('cid', models.CharField(max_length=10)),
                ('material', models.FileField(upload_to='')),
                ('date', models.DateField()),
            ],
        ),
    ]
