# Generated by Django 2.2.11 on 2020-10-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='fid',
        ),
        migrations.RemoveField(
            model_name='faculty_courses',
            name='fid',
        ),
        migrations.AddField(
            model_name='faculty',
            name='fusername',
            field=models.CharField(default='00s00', max_length=30),
        ),
        migrations.AddField(
            model_name='faculty_courses',
            name='fusername',
            field=models.CharField(default='00s00', max_length=30),
        ),
    ]
