# Generated by Django 2.2.11 on 2020-10-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20201002_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='fid',
        ),
        migrations.AddField(
            model_name='files',
            name='fusername',
            field=models.CharField(default='00s00', max_length=30),
        ),
    ]
