# Generated by Django 3.1.1 on 2020-10-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_auto_20201002_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='cid',
            field=models.CharField(default='title', max_length=10),
        ),
        migrations.AlterField(
            model_name='files',
            name='fusername',
            field=models.CharField(max_length=30),
        ),
    ]
