# Generated by Django 2.2.11 on 2020-10-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('smail', models.EmailField(max_length=254)),
                ('spass', models.CharField(max_length=15)),
                ('sdept', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='student_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('fid', models.IntegerField()),
                ('cid', models.CharField(max_length=10)),
            ],
        ),
    ]
