# Generated by Django 2.2.11 on 2020-10-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20201002_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sdept',
        ),
    ]
